[package]
authors = ["887 <2300887@gmail.com>"]
name = "httpsdns"
version = "0.1.0"

[dependencies]
chrono = "0.2.25"
dns-parser = "0.5.1"
futures = "0.1.2"
futures-cpupool = "0.1.2"
tokio-core = "0.1.0"
toml = "0.2.1"

[dependencies.tokio-tls]
git = "https://github.com/tokio-rs/tokio-tls"
optional = false
