[package]
authors = ["887 <2300887@gmail.com>"]
name = "httpsdns"
version = "0.1.0"

[dependencies]
dns-parser = "*"
futures = "*"
futures-cpupool = "0.1.2"
tokio-core = "0.1.0"
toml = "*"

[dependencies.tokio-proto]
git = "https://github.com/tokio-rs/tokio-proto"
optional = false
