[package]
authors = ["887 <2300887@gmail.com>"]
name = "httpsdns"
version = "0.1.0"

[dependencies]
chrono = "0.2.25"
dns-parser = "*"
futures = "0.1.2"
futures-cpupool = "0.1.2"
time = "0.1.35"
tokio-core = "0.1.0"
toml = "0.2.1"
